version: 2.1

# add your orb below, to be used in integration tests (note: a @dev:alpha
# release must exist.);
orbs:
  heroku: circleci/heroku@1.2.6
  anchore: anchore/anchore-engine@1

jobs:
  # This job is an example of an integration testing job.
  # This job should execute a command from your orb and verify
  # the output is as expected, otherwise the job should fail.
  #
  # Rename this job and add more as needed.
  #
  builddeploy:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - heroku/install
      - heroku/check-authentication
      - run:
          command: 'docker build -t "example/test:latest" .'
          name: build container
      - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: 'example/test:latest'
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
      - run:
          name: Check if Heroku is installed
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              echo " Heroku is not installed! "; exit 1;
            else
              echo Heroku successfully installed..
            fi
      - heroku/push-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: web
      - heroku/release-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: web

workflows:
  build:
    jobs:
      - builddeploy